version: '3.8'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=candidat'
      - 'POSTGRES_PASSWORD=maissa123456'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5431'

